### ISSUE TITLE
Too many bytes written

### ISSUE THREAD

**Issue by lxwbr** [zio/zio-lambda#136]
Looks like [this line](https://github.com/zio/zio-lambda/blob/master/lambda/src/main/scala/zio/lambda/internal/RuntimeApiLive.scala#L88) is causing an exception when too many bytes are written:

```
timestamp=2022-10-04T00:50:46.361009Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-6" java.io.IOException: java.io.IOException: too many bytes written
at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3655)
at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3646)
at zio.lambda.internal.RuntimeApiLive.$anonfun$postRequest$2(RuntimeApiLive.scala:88)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at zio.ZIOCompanionVersionSpecific.$anonfun$attempt$1(ZIOCompanionVersionSpecific.scala:105)
at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:330)
at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:448)
at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:223)
at zio.internal.FiberRuntime.run(FiberRuntime.scala:140)
at zio.internal.ZScheduler$$anon$3.run(ZScheduler.scala:424)
at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
at zio.lambda.internal.RuntimeApiLive.postRequest(RuntimeApiLive.scala:86)
at zio.lambda.internal.LoopProcessor.Live.loop(LoopProcessor.scala:32)
at zio.lambda.ZLambda.run(ZLambda.scala:24)"
```

**Comment by jrmsamson** [comment]
Hi @lxwbr, sorry for the really late response.

Could you provide more context about this error? just with the stacktrace is really hard to figure it out the actual issue

**Comment by lxwbr** [comment]
@jrmsamson sorry, my bad. I can't remember the context myself any longer. I was trying out to deploy a small example and use some AWS resources, e.g. DynamoDB and at some point I ran into issues. I will close this one
